---

- hosts: all
  become: true
  tasks:


  - name: Running Following commands just for testing
    shell: |
       cd /root/bugx_wepapp
       systemctl start bugx
       cd /root
       mkdir ansible_testing
       cd /root/ansible_testing
       touch tako 
       ll /root/bugx_wepapp > tako
    register: displayfile
      
  - debug:
      msg: "{{ displayfile.stdout_lines }}"
    when: ansible_distribution == "CentOS"