---

- hosts: all
  tasks:


  - name: Running Following commands just for testing
    command: “{{ item }}”
    loop:
      - cd /root/bugx_wepapp
      - systemctl start bugx
      - cd /root
      - mkdir ansible_testtako
      - cd /root/ansible_testing
      - touch tako