---

- hosts: all
  tasks:
  become: true

    - name: Running Following commands just for testing
      shell:
         "touch tako"
      args:
        chdir: "/root/bugx_wepapp"

    - name: new command
      shell:
         "cat passwd > /root/bugx_wepapp/tako"
      args:
        chdir: "/etc"   
        