---

- hosts: all
  become: true
  tasks:

  - name: to enbale powertools for libyaml-devel
    shell:
       "dnf -y config-manager --set-enabled powertools"
   
  - name:  install build dependencies
    shell: 
       "yum install -y git-core zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison curl sqlite-devel"
  
  - name: clonning rbenv repos from github
    shell:
       "git clone https://github.com/rbenv/rbenv.git"
    args:
      chdir: /root 

  - name: clonnig ruby-build.git repo and forward it to ~/.rbenv/plugins/ruby-build
    shell:
       "git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build" 
    

      
        