---

- hosts: all
  become: true
  tasks:

  - name: to enbale powertools for libyaml-devel
    shell:
       "dnf -y config-manager --set-enabled powertools"
   
  - name: cowsay
    shell: 
       "echo "powertools enabled succesfully"|cowsay"
    
      
        