---

- hosts: all
  become: true
  tasks:


  - name: Running Following commands just for testing
  command: “{{item}}”
  with_items:
  - cd /root/bugx_wepapp
  - systemctl start bugx
  - cd /root
  - mkdir ansible_testtako
  - cd /root/ansible_testing
  - touch tako 
  - ll /root/bugx_wepapp > tako