---

- hosts: all
  become: true
  tasks:


  - name: enable and start firewalld
    shell: |
      systemctl enable firewalld
      systemctl start firewalld

  - name: permit traffic in default zone for http service
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: permit traffic in default zone on port 4000/tcp
    ansible.posix.firewalld:
      port: 4000/tcp
      permanent: yes
      state: enabled

  - name: reload firewalld
    shell: |
      firewall-cmd --reload
      systemctl restart firewalld

  - name: enable and start bugx server
    shell: |
      systemctl daemon-reload
      systemctl enable bugx
      systemctl restart bugx