---


- hosts: all
  become: true
  tasks:


  - name: update repository
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: update repository
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name : removing nginx web server in CentOS based servers
    yum:
      name: nginx
      state: absent
    when: ansible_distribution == "CentOS"

  - name : removing nginx web server in Ubuntu based servers
    apt:
      name: nginx
      state: absent
    when: ansible_distribution == "Ubuntu"

