---

- hosts: all
  become: true
  tasks:

  
  - name: Replace between the expressions
    ansible.builtin.replace:
      path: /etc/nginx/nginx.conf
      regexp: 'listen  80 default_server;'


            

  