---

  
- hosts: all
  become: true
  tasks:

  - name: installing apache web server and git 
    package: 
         name: 
            - "{{ apache_package }}"
            - "{{ git_package }}"
         state: latest
         update_cache: yes
